name: Deploy - Production

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # - name: Cleaing Folder /var/www/agendator.velloware.com
      #   uses: appleboy/ssh-action@master
      #   with:
      #     host: ${{ secrets.HOST }}
      #     username: ${{ secrets.USERNAME }}
      #     password: ${{ secrets.PASSWORD }}
      #     port: ${{ secrets.PORT }}
      #     script: rm -r /var/www/agendator.velloware.com/*

      - name: Checkout repository
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up Node
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          
      - uses: actions/checkout@master
      - name: Copy repository contents via scp
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          PORT: ${{ secrets.PORT }}
          source: '.'
          target: '/var/www/agendator-backend.velloware.com'

      - uses: appleboy/ssh-action@master
      - name: Executing remote command
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          PORT: ${{ secrets.PORT }}s
          script: |
            sudo chown -R $USER /var/www/agendator-backend.velloware.com
            cd /var/www/agendator-backend.velloware.com
            export NVM_DIR="$HOME/.nvm"
            [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
            npm ci i
            npm run build
            npm run prisma:deploy
            pm2 link ${{ secrets.PM2ATEST }} ${{ secrets.PM2BTEST }}
            MULTPROCESS=true pm2 start ecosystem.config.js
            curl --request POST --url https://dash.velloware.com/api/notification --header 'Content-Type: application/json' --data '{"message": "\n✔ Deploy Agendator Backend-${{ github.ref_name }} on agendator-backend.velloware.com 📣\n"}'
